# Site
name: "Better Version"
title: "Mediumish"
description: "Better Today, Brilliant Tomorrow."
logo: 'assets/images/logo.webp'
favicon: 'assets/images/logo.webp'
baseurl: 
url: https://wordwhisperer.co
google_analytics: 'G-6H46KNRCC3'
disqus: 'demowebsite'
mailchimp-list: 'https://wordwhisperer.us17.list-manage.com/subscribe?u=90859a536853310a5315c62e8&id=817c6be5e5'
contact_form: 'https://formbold.com/s/9BgYm'
include: ["_pages"]
permalink: /blog/:title/

sass:
  style: compressed


jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:  

# Authors
authors:
  sal:
    name: Better Version
    display_name: Better Version
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 
    web: 
    twitter: 
    description: "I feel honored to be a part of your learning and growth journey. Your time and mental resources are extremely valuable, so I will do my best to make every moment you are here worth."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minifier
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
